/**********************************************************************************************************************
 * \file SPI_DMA.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "SPI_DMA.h"
#include "IfxPort.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define QSPI1_MASTER                &MODULE_QSPI1               /* SPI Master Hardware module                       */

#define ISR_PRIORITY_QSPI1_TX       1                           /* Define the QSPI1 transmit interrupt priority     */
#define ISR_PRIORITY_QSPI1_RX       2                           /* Define the QSPI1 receive interrupt priority      */
#define ISR_PRIORITY_QSPI1_ER       10                          /* Define the QSPI1 error interrupt priority        */

#define ISR_PRIORITY_DMA_CH1        50                          /* Define the DMA channel1 interrupt priority       */
#define ISR_PRIORITY_DMA_CH2        51                          /* Define the DMA channel2 interrupt priority       */

#define ISR_PROVIDER_QSPI1          IfxSrc_Tos_cpu0             /* Define the QSPI1 interrupt provider              */

#define ISR_PROVIDER_DMA_CH1        IfxSrc_Tos_cpu0             /* Define the DMA Channel1 interrupt provider       */
#define ISR_PROVIDER_DMA_CH2        IfxSrc_Tos_cpu0             /* Define the DMA Channel2 interrupt provider       */

#define MASTER_CHANNEL_BAUDRATE     1000000                     /* Master channel baud rate                         */

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
qspiDma g_qspiDma;                                              /* Global handle for QSPI communication             */

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
static void initQSPI1Master(void);
static void initQSPI1MasterChannel(void);
static void initQSPI(void);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
IFX_INTERRUPT(QSPI1ErrorISR, 0, ISR_PRIORITY_QSPI1_ER);         /* SPI Master Error Interrupt definition            */
IFX_INTERRUPT(DMAChn1ISR, 0, ISR_PRIORITY_DMA_CH1);             /* DMA Channel 1 Interrupt definition               */
IFX_INTERRUPT(DMAChn2ISR, 0, ISR_PRIORITY_DMA_CH2);             /* DMA Channel 2 Interrupt definition               */

/* Handle QSPI1 Error interrupt */
void QSPI1ErrorISR(void)
{
    IfxCpu_enableInterrupts();
    IfxQspi_SpiMaster_isrError(&g_qspiDma.spiMaster);
}

/* Handle DMA Channel 1 interrupt */
void DMAChn1ISR(void)
{
    IfxCpu_enableInterrupts();
    IfxQspi_SpiMaster_isrDmaTransmit(&g_qspiDma.spiMaster);
}


/* Handle DMA Channel 2 interrupt */
void DMAChn2ISR(void)
{
    IfxCpu_enableInterrupts();
    IfxQspi_SpiMaster_isrDmaReceive(&g_qspiDma.spiMaster);
}

/* This function initializes QSPI1 in master mode */
static void initQSPI1Master(void)
{
    IfxQspi_SpiMaster_Config spiMasterConfig;                           /* Define the Master Configuration          */

    IfxQspi_SpiMaster_initModuleConfig(&spiMasterConfig, QSPI1_MASTER); /* Initialize it with default values        */

    const IfxQspi_SpiMaster_Pins QSPI1Masterpins = {
        &IfxQspi1_SCLK_P10_2_OUT, IfxPort_OutputMode_pushPull,          /* SCLK Pin                          (CLK)  */
        &IfxQspi1_MTSR_P10_3_OUT, IfxPort_OutputMode_pushPull,          /* Master Transmit Slave Receive Pin (MOSI) */
        &IfxQspi1_MRSTA_P10_1_IN, IfxPort_InputMode_pullDown,           /* Master Receive Slave Transmit Pin (MISO) */
        IfxPort_PadDriver_cmosAutomotiveSpeed3                          /* Pad driver mode                          */
    };
    spiMasterConfig.pins = &QSPI1Masterpins;                            /* Assign Master Pins                       */
    
    spiMasterConfig.dma.useDma = TRUE;
    spiMasterConfig.dma.txDmaChannelId = IfxDma_ChannelId_1;
    spiMasterConfig.dma.rxDmaChannelId = IfxDma_ChannelId_2;
    
    spiMasterConfig.base.txPriority = ISR_PRIORITY_DMA_CH1;
    spiMasterConfig.base.rxPriority = ISR_PRIORITY_DMA_CH2;
    spiMasterConfig.base.erPriority = ISR_PRIORITY_QSPI1_ER;
    spiMasterConfig.base.isrProvider = ISR_PROVIDER_QSPI1;

    /* Initialize the QSPI Master module using the user configuration */
    IfxQspi_SpiMaster_initModule(&g_qspiDma.spiMaster, &spiMasterConfig);
}

/*  This function initializes QSPI1 channel. */
static void initQSPI1MasterChannel(void)
{
    IfxQspi_SpiMaster_ChannelConfig spiMasterChannelConfig;             /* Define the Master Channel Configuration  */

    IfxQspi_SpiMaster_initChannelConfig(&spiMasterChannelConfig, &g_qspiDma.spiMaster); /* Initialize it with default values */

    spiMasterChannelConfig.base.baudrate = MASTER_CHANNEL_BAUDRATE;     /* Set SCLK frequency to 1 MHz              */

    const IfxQspi_SpiMaster_Output QSPI1SlaveSelect = {
        &IfxQspi1_SLSO9_P10_5_OUT, IfxPort_OutputMode_pushPull,         /* Slave Select Pin (CS)                    */
        IfxPort_PadDriver_cmosAutomotiveSpeed1                          /* Pad driver mode                          */
    };
    spiMasterChannelConfig.sls.output = QSPI1SlaveSelect;

    /* set the transfer data width */
    spiMasterChannelConfig.base.mode.dataWidth      = 16;
    spiMasterChannelConfig.base.mode.csLeadDelay    = SpiIf_SlsoTiming_1;
    spiMasterChannelConfig.base.mode.csTrailDelay   = SpiIf_SlsoTiming_0;
    spiMasterChannelConfig.base.mode.csInactiveDelay= SpiIf_SlsoTiming_0;
    spiMasterChannelConfig.base.mode.shiftClock     = SpiIf_ShiftClock_shiftTransmitDataOnTrailingEdge;

    /* Initialize the QSPI Master channel using the user configuration */
    IfxQspi_SpiMaster_initChannel(&g_qspiDma.spiMasterChannel, &spiMasterChannelConfig);

}

/* This function initializes the QSPI modules */
void initQSPI(void)
{
    /* Initialize the Master */
    initQSPI1Master();
    initQSPI1MasterChannel();
}

/* This function ensures the QSPI communication between Master and Slave and checks whether
 * the data transfer was correct or not
 */
void transferData(uint8 * data, uint16 size)
{
    /* Start SPI Master communication */
    IfxQspi_SpiMaster_exchange(
            &g_qspiDma.spiMasterChannel,
            data,
            0,
            size);
}
